version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  clone_repo:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
    git: CF-default
  execute_unit_test:
    title: Unit test
    stage: test
    image: 'maven:3.6.2-jdk-11-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/.m2 test
  build_docker_image:
    title: Building Docker Image
    type: build
    stage: build
    image_name: my-app-image
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: docker/Dockerfile
