version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  CloneRepo:
    title: Cloning Repository
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
    git: github
  ExecuteUnitTest:
    title: Unit test
    stage: test
    working_directory: '${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}'
    image: 'maven:3.6.1-jdk-11-slim'
    commands:
      - mvn -Dmaven.repo.local='${{CF_VOLUME_PATH}}/m2_repository' test
