version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  SetStatusToPrepareToPending:
    title: Set Prepare Stage to Pending
    image: cloudposse/github-status-updater
    environment:
      - GITHUB_ACTION=update_state
      - GITHUB_TOKEN=${{GITHUB_TOKEN}}
      - GITHUB_OWNER=${{CF_REPO_OWNER}}
      - GITHUB_REPO=${{CF_REPO_NAME}}
      - GITHUB_REF=${{CF_REVISION}}
      - GITHUB_CONTEXT=Prepare
      - GITHUB_STATE=pending
      - GITHUB_DESCRIPTION=Executing Prepare Stage
      - GITHUB_TARGET_URL=${{CF_BUILD_URL}}
  CloneRepo:
    title: Cloning Repository
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
    git: github
  SetStatusToPrepareToDone:
    title: Set Prepare Stage to Done
    image: cloudposse/github-status-updater
    environment:
      - GITHUB_ACTION=update_state
      - GITHUB_TOKEN=${{GITHUB_TOKEN}}
      - GITHUB_OWNER=${{CF_REPO_OWNER}}
      - GITHUB_REPO=${{CF_REPO_NAME}}
      - GITHUB_REF=${{CF_REVISION}}
      - GITHUB_CONTEXT=Prepare
      - GITHUB_STATE=success
      - GITHUB_DESCRIPTION=Prepare Stage Successful
      - GITHUB_TARGET_URL=${{CF_BUILD_URL}}
  ExecuteUnitTest:
    title: Unit test
    stage: test
    working_directory: '${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}'
    image: 'maven:3.6.1-jdk-11-slim'
    commands:
      - mvn -Dmaven.repo.local='${{CF_VOLUME_PATH}}/m2_repository' test
  BuildJar:
    title: Build Executable
    stage: build
    working_directory: './${{CF_REPO_NAME}}'
    image: 'maven:3.6.1-jdk-11-slim'
    commands:
      - mvn -Dmaven.repo.local='${{CF_VOLUME_PATH}}/m2_repository' package -Dmaven.test.skip=true
  BuildDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: circleci-test
    working_directory: '${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}'
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    dockerfile: docker/Dockerfile
  PushDockerImage:
    stage: build
    type: push
    title: Pushing to Docker Hub
    candidate: ${{BuildDockerImage}}
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
    registry: dockerhub
    image_name: sushantparkhi/circleci-test
