version: '1.0'
stages:
  - prepare
  - test
  - build
steps:
  CloneRepo:
    title: Cloning main repository...
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    stage: prepare
    git: CF-default
  ExecuteUnitTest:
    title: Unit test
    stage: test
    working_directory: ./
    image: 'maven:3.6.1-jdk-11-slim'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository test
  ExecuteDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: my-app-image
    working_directory: ./
    tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
    dockerfile: docker/Dockerfile
